import localFont from 'next/font/local';
import './globals.css';
import Logo from './components/Logo';
import { logo } from '../../public/assets';
import Button from './components/Button';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata = {
	title: 'AgroVision | ',
	description: 'Generated by create next app',
	author: 'Nkwuda Theophilus',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable}text-white antialiased`}
			>
				<header className='bg-black/90 text-white '>
					<nav className='flex items-center justify-between px-10 py-3 pt-10'>
						<Logo />
						<ul className='flex items-center justify-around gap-x-10 font-[600] capitalize '>
							<li>
								<a href='/'> Home</a>
							</li>
							<li>
								<a href='/about'> About</a>
							</li>
							<li>
								<a href='/features'> Features</a>
							</li>
							<li>
								<a href='/pricing'> Pricing</a>
							</li>
							<li>
								<a href='/download'> Download</a>
							</li>
						</ul>
						<Button title={'sign up'} />
					</nav>
				</header>
				{children}
				<footer></footer>
			</body>
		</html>
	);
}
